[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
auto_detect_solc = true

[dependencies]
"@openzeppelin-contracts" = "5.2.0"

[soldeer]
remappings_generate = false
recursive_deps = true

remappings = [
    "@openzeppelin-contracts-5=dependencies/@openzeppelin-contracts-5.2.0/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
