[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
auto_detect_solc = true

remappings = [
    "@openzeppelin-contracts-5=dependencies/@openzeppelin-contracts-5.2.0/",
    "forge-std-1.9.6/=dependencies/forge-std-1.9.6/",
]

[dependencies]
"@openzeppelin-contracts" = "5.2.0"
forge-std = "1.9.6"

[soldeer]
remappings_generate = true
remappings_location = "config"
remappings_version = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
